<a href="https://colab.research.google.com/github/155shubham/Pytorch_Learning/blob/main/Tensors/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What are tensors?

Tensors are specialiased data structure that are very similar to arrays and matrices.
They are very simila to Numpy ndarrays execpt that tensors run on GPUs or other hardware accelerators.
Tensors are optimised for automatic differentiation.

We will see below some samples and will start by loading torch and numpy library.

In [ ]:
import torch
import numpy as np

Initialising a Tensor

Tensors can be initialised in following various ways:

1. Directly From data

In [5]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [7]:
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
type(x_data)

torch.Tensor

2. From a NumPy array

In [11]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [12]:
x_np

tensor([[1, 2],
        [3, 4]])

In [13]:
type(x_np)

torch.Tensor

Note:- tensors can also converted to numpy arrays.

3. From another tensor

    The new tensors retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [14]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [17]:
type(x_ones)

torch.Tensor

In [18]:
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.1564, 0.6798],
        [0.7349, 0.4220]]) 



In [19]:
type(x_rand)

torch.Tensor

4. With random or constant values

    shape is a tuple of tensor dimensions. In the function below, it determines the dimensionality of the output tensor.

In [31]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7716, 0.7268, 0.5986],
        [0.1206, 0.3263, 0.7931]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [32]:
type(rand_tensor)

torch.Tensor

In [33]:
type(ones_tensor)

torch.Tensor

In [34]:
type(zeros_tensor)

torch.Tensor

Attributes of a Tensor

Tensor attributes describe their shpae, datatype, and the device on which they are stored.

In [36]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
